name: Android Build & Release

on:
  pull_request:
    branches:
      - shopping_dashbroad
  push:
    branches:
      - master

jobs:
  build:
    name: Build & Release APK
    runs-on: ubuntu-22.04
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      # Step 3: Grant Gradle wrapper execution permissions
      - name: Change Gradle Wrapper Permissions
        run: chmod +x ./gradlew

      # Step 4: Install Dependencies
      - name: Build Dependencies
        run: ./gradlew dependencies

      # Step 5: Build APK with Gradle
      - name: Build APK
        run: ./gradlew assembleRelease

      # Step 6: Debug APK Output
      - name: Debug APK Output
        run: ls -R app/build/outputs/

      # Step 7: Upload APK artifact (Updated Path)
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app_release
          path: app/build/outputs/apk/release/*.apk

  release:
    name: Release APK
    needs: build
    runs-on: ubuntu-22.04
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Push APK artifact to GitHub Releases
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: app/build/outputs/apk/release/*.apk
          tag: v1.0.${{ github.run_number }}
          name: "Android Release v1.0.${{ github.run_number }}"
          token: ${{ secrets.GITHUB_TOKEN }}
